### PR TITLE
follow migration guide for ipywidgets 7 -> 8

### PR DESCRIPTION
**Pull request by renefritze**
This is mostly updating dependency pins.

The [guide](https://ipywidgets.readthedocs.io/en/stable/migration_guides.html#updating-the-webpack-publicpath-configuration) also mentions updating the webpack config, but that is out of my range.

### CODE REVIEW

**Comment by renefritze** [comment]
Here's a binder link for the branch [Binder](https://mybinder.org/v2/gh/renefritze/K3D-jupyter/ipywidgets_update)

Sadly this does not fix #371

**Comment by agoose77** [comment]
Bumping the upper bound for `ipywidgets` only means that a future 9.x release will be considered compatible.

The next thing we need to do fix ipywidgets 8 support is [update the BackBone modules](https://ipywidgets.readthedocs.io/en/stable/migration_guides.html#backbone-extend) in [`k3d.js`](https://github.com/K3D-tools/K3D-jupyter/blob/main/js/src/k3d.js)

**Comment by renefritze** [comment]
> Bumping the upper bound for ipywidgets only means that a future 9.x release will be considered compatible! 

Are you referring to [this](https://github.com/K3D-tools/K3D-jupyter/pull/377/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R42) 
I read the guide as that's matching the pin for `<9`.

**Comment by renefritze** [comment]
See #378 instead.

**Pull request closed without merging**
