### PR TITLE
Finalize #378

### PR DESCRIPTION
**Pull request by renefritze**
This PR is based on @agoose77's #378. I think fixed the `fflate` [problems](https://github.com/K3D-tools/K3D-jupyter/pull/378#issuecomment-1268178355) issue, which in turn finally seems to get rid of the model load errors.

At least the examples I tried on mybinder now work in jupyterlab, but not in classic notebook. 
Jupyter does not find the right `k3d.js` to serve. 
 [Binder](https://mybinder.org/v2/gh/pymor/K3D-jupyter/finalize_378)

@agoose77 if you prefer I could make this a PR against your branch instead

### CODE REVIEW

**Comment by renefritze** [comment]
The `visual_*text*` tests started failing some time after https://github.com/K3D-tools/K3D-jupyter/pull/386/commits/23d3e82d3d0178035234da26b71f2089ab2ce2be
Since nothing touched actual library code, I think I'll  assume some default in font rendering changed. The rendered text now generally looks a little taller and more narrow. 
[text_pngs.tar.gz](https://github.com/K3D-tools/K3D-jupyter/files/10056764/text_pngs.tar.gz)
Example diff
text_diff

I'm therefore replacing the old references

**Comment by renefritze** [comment]
So I rebased on `devel` to fix the text tests. This is now ready to merge and release AFAICS, @artur-trzesiok

**Comment by artur-trzesiok** [comment]
Amazing work! Thank you a lot!

**Comment by artur-trzesiok** [comment]
@renefritze and @agoose77 I'm ready to do a release from main. Can I gently ask you to tests whl package before I will push that to pypi and conda-forge? https://cubeproject.pl/k3d-2.15.0-py3-none-any.whl

And most of all - thanks again for handling all that stuff. Great help! I had to put on hold k3d for a while and I'm really happy that you take responsobilities for doing maintanance!

**Comment by renefritze** [comment]
Sorry, no can do. I'm AFK for the next two weeks.

**Comment by renefritze** [comment]
> @renefritze and @agoose77 I'm ready to do a release from main. Can I gently ask you to tests whl package before I will push that to pypi and conda-forge? https://cubeproject.pl/k3d-2.15.0-py3-none-any.whl
> 
> And most of all - thanks again for handling all that stuff. Great help! I had to put on hold k3d for a while and I'm really happy that you take responsobilities for doing maintanance!

Tested the whl and it works for me too! 
I would be very happy if you release this soon!

**Comment by artur-trzesiok** [comment]
Hi! I will do a relaease :)

**Comment by artur-trzesiok** [comment]
@renefritze what with conda-forge ? Should we use https://github.com/conda-forge/k3d-feedstock without any modification? I ask you because k3d-feedstock is mostly done by you (thanks to that!)

**Comment by renefritze** [comment]
> We will need to update the recipe. I can try and take a look.

The version update is [automatic](https://github.com/conda-forge/k3d-feedstock/pull/42), what else do you have in mind?

**Comment by renefritze** [comment]
> The `host` dependencies should be updated to reflect the new build system. [conda-forge/k3d-feedstock#43](https://github.com/conda-forge/k3d-feedstock/pull/43)

Right. I did not consider that switch :+1:

**Comment by artur-trzesiok** [comment]
I merged k3d-feedback and re-run a check

**Comment by artur-trzesiok** [comment]
> It will fail - I missed a dependency 🤦
> 
> I'll make another PR.

Don't worry. I'm happy that we are close to have working solution :). Thanks again for your contributions!

**Pull request merged**
