### PR TITLE
Update transform.py because of RuntimeError

### PR DESCRIPTION
**Pull request by xenolex**
Got
RuntimeError: dictionary changed size during iteration on locals iteration, because locals, change when you iter over them,

### CODE REVIEW

**Comment by xenolex** [comment]
@artur-trzesiok please take a look

**Review by tgandor — APPROVED** [review]
I'm not sure why we need to copy the `locals()` dictionary, but it's OK with me.

**Comment by tgandor** [comment]
Oops, you've just written above, that locals() is modified during iteration; I thought that it returned a 'read-only' view of the local scope, and not the real dict instead. @artur-trzesiok this should be merged.

**Comment by artur-trzesiok** [comment]
@xenolex Thanks for good spoting and Fix! @tgandor thanks for verification!

**Pull request merged**
