### PR TITLE
Update to 'standard' jupyter packaging

### PR DESCRIPTION
**Pull request by vidartf**
Updates setup code to use the recently created ['jupyter-packaging'](https://github.com/jupyter/jupyter-packaging) setup utilities , in order to keep setup.py clean and robust.

### CODE REVIEW

**Comment by artur-trzesiok** [comment]
Thanks!

**Comment by artur-trzesiok** [comment]
After this PR our wheel dosen't contain js files. Could you look at this?

**Comment by artur-trzesiok** [comment]
It's seems to be necessary right now to have 3 steps installation process insted of 2 steps:

`$ pip install k3d
$ jupyter nbextension install --py --sys-prefix k3d
$ jupyter nbextension enable --py --sys-prefix k3d`

Before your PR middle command can be avoided. Could you provide more info about this?

**Comment by vidartf** [comment]
I think that you could only skip that step when you were using jupyter-pip (before the refactor?). I don't think that this PR should have changed the behavior.

**Pull request merged**
